### ISSUE TITLE
Layout problems

### ISSUE THREAD

**Issue by realGWM** [librehat/yapstocks#11]
Hey, thanks for your work on this.
Just wanted to let you know (in case you are still maintaining this), that there is some kind of a layout problem (not sure if it is app's problem, or something wrong with my system, but this is the only app I have problems with).
![photo_2022-01-28_20-56-36](https://user-images.githubusercontent.com/19240800/151612961-fc037ad1-62db-455c-b76e-000648cdf749.jpg)
![photo_2022-01-28_20-56-38](https://user-images.githubusercontent.com/19240800/151612964-0eb53c63-bfdb-40df-a710-5b3f17211b7f.jpg)

**Comment by lah7** [comment]
I can confirm having the same issue. I think it started with one of KDE's updates a few weeks ago.

OS: Arch Linux
Plasma: 5.23.5
KDE Frameworks: 5.90.0
Qt Version: 5.15.2
X11 / NVIDIA

**Comment by MrLavender** [comment]
Same here. It seems to be not including headerRow in layout calculations. E.g. a hack fix for mainView is

```diff
        PlasmaComponents3.ScrollView {
            anchors.fill: parent
+           anchors.topMargin: headerRow.height
            ListView {
                id: view
```

Operating System: Manjaro Linux
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Graphics Platform: X11

**Comment by librehat** [comment]
Hi all, I don't use Linux desktop at the moment. If you have a fix, I'm happy to accept the PR.

**Comment by librehat** [comment]
Back to using Linux as my daily driver, will fix this
