### ISSUE TITLE
Not working any more on KDE plasma wayland

### ISSUE THREAD

**Issue by hifi25nl** [librehat/yapstocks#14]
It was working until few days ago. Now the plasmoid is empty.
Could you fix it?

Archlinux Plasma 5.27.4, fully updated system

**Comment by librehat** [comment]
I can't reproduce it on my OpenSUSE Leap. You're welcome to fix it yourself

**Comment by hifi25nl** [comment]
Ok, after some KDE updating  now is back to normal.

**Comment by hifi25nl** [comment]
I will close
