### ISSUE TITLE
v4.3 - Daily change showing 0.00% or N/A (nan%) for ALL equities

### ISSUE THREAD

**Issue by YoshShmenge** [librehat/yapstocks#15]
Thanks for the widget! Installed via the "Download New Plasma Widgets" dialog. Daily price change showing 0.00% or N/A (nan%) for all the equities I added. NaN seems to only be present on stocks where price<1.

Tested on Kubuntu 22.04.2 LTS. All other functions are working - prices, stock info, charts.

Plasma 5.24.7
KDE frameworks 5.92.0
Qt 5.15.3

**Comment by librehat** [comment]
Could you share one example Equity symbol that you used?

**Comment by YoshShmenge** [comment]
Hi, was just about to update. After a reboot - first reboot since I added the symbols, it now works. It is showing the days change correctly.

**Comment by librehat** [comment]
OK. I'll close this then
