### ISSUE TITLE
No values displayed on widget

### ISSUE THREAD

**Issue by abrasiveteapot** [librehat/yapstocks#16]
Yapstocks has been working fine for years however now no longer displays the feed. Screenshot attached. Quite probably related to a version getting updated but not sure where to start testing to establish what the cause is.

![image](https://github.com/librehat/yapstocks/assets/133246886/74d6fc42-09dc-4eac-9b38-2ce3c574f9bf)

System version levels: 

https://old.reddit.com/r/kde/comments/13ehbyc/kde_widget_yapstocks_no_longer_displaying_values/jjptqh4/

KDE details

Operating System: Arch Linux

KDE Plasma Version: 5.27.5

KDE Frameworks Version: 5.105.0

Qt Version: 5.15.9

Kernel Version: 6.3.1-arch1-1 (64-bit)

Graphics Platform: Wayland

OS details

OS: Arch Linux x86_64

Kernel: 6.3.1-arch1-1

Packages: 1852 (pacman), 18 (flatpak)

Shell: bash 5.1.16

Resolution: 1920x1080

DE: Plasma 5.27.5

WM: kwin

WM Theme: Oxygen

Theme: Breeze Light [Plasma], Breeze [GTK3]

Icons: [Plasma], Relax-Light-Icons [GTK2/3]

qt5-charts version is 5.15.9-1

**Comment by librehat** [comment]
Thanks for reporting this. I can confirm this is an issue.

It seems that the API to get the quotes is now throwing "Unauthorized" error.

Checking the Yahoo Finance website, it seems a valid "crumb" is now needed, which in turn needs a valid cookie.

I'll see if I can spare some time to fix this in the coming weeks.

**Comment by igrekster** [comment]
This workaround helped me:
https://stackoverflow.com/questions/76059562/yahoo-finance-api-get-quotes-returns-invalid-cookie

> I had the same issue today. Change the "v7" to "v6" in the URL in your GET request. It will then work, at least for now. Because the Yahoo Finance API hasn't been officially supported since 2017, we do what we can with it.

**Comment by MrLavender** [comment]
Unfortunately v6 no longer works either since a couple of days ago, and it looks like that API is now completely dead for the foreseeable future.

https://stackoverflow.com/a/76333014

So I guess Yapstocks is dead too unless the data can be obtained somewhere else.

**Comment by librehat** [comment]
> Unfortunately v6 no longer works either since a couple of days ago, and it looks like that API is now completely dead for the foreseeable future.
> 
> https://stackoverflow.com/a/76333014
> 
> So I guess Yapstocks is dead too unless the data can be obtained somewhere else.

In the code, there is this "resolveQuote" function that returns quote for a single symbol. Does that one still work? If that no longer works, agreed then this widget is dead :(

**Comment by MrLavender** [comment]
The endpoint in that function definitely works (for now) but I'm not a Javascript developer so don't know how to easily run and test the function itself.

E.g. https://query1.finance.yahoo.com/v10/finance/quoteSummary/MSFT?modules=price

**Comment by librehat** [comment]
Please try v4.5

**Comment by igrekster** [comment]
> Please try v4.5

Works for me -- thank you very much for fixing it.

**Comment by MrLavender** [comment]
Working for me too, thanks!

**Comment by abrasiveteapot** [comment]
Minor bug in the display. The change in price is being marked as a percentage but displayed as decimal. I.e a $2.30 increase on a 215.70 base value is marked as 0.01% as opposed to 1%

![image](https://github.com/librehat/yapstocks/assets/133246886/714a4ae5-c179-45d6-be9b-60a454d9fba0)
