### ISSUE TITLE
Widget stopped working as Yahoo has closed its endpoint

### ISSUE THREAD

**Issue by pverghese** [librehat/yapstocks#19]
the v10 endpoint needs a cookie and crumb
crumb endpoint: https://query2.finance.yahoo.com/v1/test/getcrumb 
--this needs cookie to be set which requires a request to https://finance.yahoo.com and saving the cookie
after the cookie and crumb have been got, you can make the request to the api endpoint with &crumb='...'

**Comment by librehat** [comment]
Confirmed this is no longer working. I won't have time updating to support their new endpoint but happy to review PRs if anyone's willing

**Comment by igrekster** [comment]
`v6` still works fine for me.

**Comment by librehat** [comment]
> `v6` still works fine for me.
> ```
> `https://query1.finance.yahoo.com/v6/finance/quoteSummary/${symbol}?modules=price`
> ```

Please open a PR updating the API in the code, thank you

**Comment by pverghese** [comment]
Made a PR for it. https://github.com/librehat/yapstocks/pull/20

**Comment by C8forT** [comment]
Confirmed that V6 still works.  I manually changed it at lines 87 and 177 in ~/.local/share/plasma/plasmoids/com.librehat.yapstocks/contents/code/yahoofinance.mjs
(I posted this so others can make the change to get YapStocks working until the update comes through, which for me has not happened yet.)

**Comment by librehat** [comment]
Thanks all. 4.6 released now
