### ISSUE TITLE
the widget works fine with plasma-sdk, but on my desktop it looks like no data

### ISSUE THREAD

**Issue by rudy880719** [librehat/yapstocks#21]
I am attaching two screenshots of the widget on my desktop and the widget in plasma-sdk.
In a screenshot you see the properties of my computer and the widget that does not show information, in the other screenshot you see the widget working when I execute sh run_plasmoid.sh
 please could you help me
![Screenshot_20230804_112542](https://github.com/librehat/yapstocks/assets/76542704/cec080ad-6784-4674-b537-3546821e4244)
![Screenshot_20230804_112801](https://github.com/librehat/yapstocks/assets/76542704/334ef332-6c4b-4cd3-b89c-a610898330a5)

**Comment by librehat** [comment]
latest master wasn't released

**Comment by librehat** [comment]
Please install 4.6 that was just released

**Comment by rudy880719** [comment]
thank you, work fine..
