### ISSUE TITLE
Sorting Stocks

### ISSUE THREAD

**Issue by deckardstp** [librehat/yapstocks#4]
Hi,

I would really appreciate a feature to sort the stocks like alphabetical. As soon as you have numerous entries it's difficult to deal with.

Thanks for the great work!

**Comment by librehat** [comment]
It's on the plan to add a feature to sort the stocks in the Configuration dialog. My original idea was drag & drop. We can have both drag and drop to manually adjust the order, and an action button to sort it by name (ascending and descending)

**Comment by deckardstp** [comment]
From a UX perspective both solutions would be great. Drag and drop seems to be a good idea, since some stocks start with numbers for example. So there would be an opportunity to manually adjust single values after sorting them for descending initially.

**Comment by librehat** [comment]
This is now supported in the `master`. Will be released under version `3.0`
