### ISSUE TITLE
No way to enter symbol (KDE Frameworks < 5.70)

### ISSUE THREAD

**Issue by dpand000** [librehat/yapstocks#7]
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-58-generic
OS Type: 64-bit
Processors: 4 × Intel® Core™ i7-6500U CPU @ 2.50GHz
Memory: 7.7 GiB of RAM
![image](https://user-images.githubusercontent.com/75903050/101988741-a5073600-3cc1-11eb-9178-c589409f56c7.png)

The text box to enter is not showing. I tried finding something on the forums, however,if there is already a solution. I apologise.
PS: I have tried rebooting

**Comment by librehat** [comment]
Strange, it seems some QML components are not loaded. Can you try to clone this project and run `run_plasmoid.sh` in the terminal to see if there is any error printed?

**Comment by dpand000** [comment]
Ok I cloned and ran it 
this was the output:

_plasmoidviewer: no process found
/home/hari-om/yapstocks/run_plasmoid.sh: line 12: plasmoidviewer: command not found_

I ran it a few more times. Output:

_rm: cannot remove '/home/hari-om/.cache/plasma-svgelements-*': No such file or directory
plasmoidviewer: no process found
/home/hari-om/yapstocks/run_plasmoid.sh: line 12: plasmoidviewer: command not found_

**Comment by librehat** [comment]
Seems you need to first install `plasma-sdk` to debug this

**Comment by dpand000** [comment]
I installed plasma sdk
Output:

plasmoidviewer: no process found
QML debugging is enabled. Only use this in a safe environment.
qml: View QML loaded
org.kde.plasmaquick: Applet preload policy set to 1
file:///usr/share/plasma/wallpapers/org.kde.image/contents/ui/main.qml:76:9: Unable to assign [undefined] to QStringList
file:///usr/share/plasma/wallpapers/org.kde.image/contents/ui/main.qml:75:9: Unable to assign [undefined] to int
file:///usr/share/plasma/wallpapers/org.kde.image/contents/ui/main.qml:75:9: Unable to assign [undefined] to int
file:///usr/share/plasma/wallpapers/org.kde.image/contents/ui/main.qml:76:9: Unable to assign [undefined] to QStringList
Toolbox not loading, toolbox package is either invalid or disabled.
qml: New Containment: ContainmentInterface(0x55deed44e2f0)
file:///home/hari-om/yapstocks/plasmoid/contents/ui/main.qml:178:5: QML BusyIndicator: Binding loop detected for property "implicitHeight"
trying to show an empty dialog
trying to show an empty dialog
trying to show an empty dialog

**Comment by librehat** [comment]
When you run the script can you see a widget running? Did you try to go to the settings pop up? (If you could record the window/screen, that'd be very helpful).

I suspect this is probably that you missed some runtime dependencies

**Comment by wooyek** [comment]
![Uploading image.png…]()

**Comment by dpand000** [comment]
Sorry for the late response
And this is what runs 
![image](https://user-images.githubusercontent.com/75903050/102696857-81ab3080-4257-11eb-920b-aa976a8ab2d9.png)
Sorry I am new to Kubuntu and linux) have no programming experience,

**Comment by librehat** [comment]
@dpand000 can you click the _configure_ button left to "Configure Containment" to see if you can see the "Symbols" settings correctly?

**Comment by dpand000** [comment]
![image](https://user-images.githubusercontent.com/75903050/102783125-79223980-43c0-11eb-9fba-c40e9a940c16.png)

**Comment by librehat** [comment]
Thank you for your update. It looks like yet another Ubuntu packaging issues (old Plasma packages).
Will try to change the components or something to satisfy Ubuntu 20.04.

**Comment by librehat** [comment]
@dpand000 I checked the KDE documentation and Ubuntu packages. Unfortunately, it seems that `qml-module-org-kde-kirigami2` package in Ubuntu 20.04 is too old.
I would suggest you to try to upgrade to Ubuntu 20.10 if that's a choice and then this will work.

**Comment by FunWithUrban** [comment]
Would love for this to to work on 20.04 as its an LTS release. I would like to stay on the LTS realease because currently there are no features I need in 20.10 so its not worth the upgrade for me just for this widget.

**Comment by librehat** [comment]
@FunWithUrban If anyone is happy to write a PR and test it in their Ubuntu 20.04 then I'm happy to review the changes. The issue is that some Kirigami components don't exist in Ubuntu 20.04 (if anyone needs a clue)

**Comment by FunWithUrban** [comment]
@librehat Is it possible to install the Kirigami components dependancies manualy to allow this to work on 20.04? If so could you maybe add a tutorial section to the read.me?

**Comment by medisoft** [comment]
I created a PR to fix this into KDE for Kubuntu/Ubuntu 20.04

**Comment by librehat** [comment]
Please install v4.2 from the store
